### PR TITLE
Overlapping data, copy on click and reset button, no caps in button labels, abbreviation explanation, compensation links size, optimize position of labels in buttons

### PR DESCRIPTION
**Pull request by VirginiaBalseiro-Zuehlke**
As discussed these are my fixes for the overlapping while keeping the previous format, the functionality for copying upon clicking and the reset button to empty the input box.

### CODE REVIEW

**Comment by VirginiaBalseiro-Zuehlke** [comment]
Fixed caps in button labels

**Comment by VirginiaBalseiro-Zuehlke** [comment]
Added explanation for BTC abbreviation.

**Comment by VirginiaBalseiro-Zuehlke** [comment]
Fixed compensation links size.

**Comment by OleGiebel** [comment]
Hey @VirginiaBalseiro-Zuehlke! General feedback from reviewing the changes: Try to see if you can move the `!important` changes to uikit sass variables (variables.scss) (https://sass-lang.com/documentation/variables) and migrate some cascading styles into mixins or extensions (https://sass-lang.com/documentation/at-rules/mixin).

**Pull request closed without merging**
